### ISSUE TITLE
Is it right to get such result with two fonts input？

### ISSUE THREAD

**Issue by Johnson-yue** [clovaai/lffont#10]
Hi ， I using two font for testing the pretrained weight there are 8 characters every font， you can download and test it。
![C2232_攀_256](https://user-images.githubusercontent.com/10268274/94389649-028bec00-0183-11eb-93ea-c9a0d44af5d2.png)
![C2366_晴_256](https://user-images.githubusercontent.com/10268274/94389651-03bd1900-0183-11eb-9731-1ba204c703a4.png)
![C3639_癜_256](https://user-images.githubusercontent.com/10268274/94389652-0455af80-0183-11eb-804e-90bdfc471eae.png)
![C3844_碱_256](https://user-images.githubusercontent.com/10268274/94389655-04ee4600-0183-11eb-80e5-55d246b03ede.png)
![C4775_荷_256](https://user-images.githubusercontent.com/10268274/94389656-0586dc80-0183-11eb-8290-b5f85eecaddb.png)
![C5810_郗_256](https://user-images.githubusercontent.com/10268274/94389657-061f7300-0183-11eb-8810-4b2c4e8b6c43.png)
![C6265_霄_256](https://user-images.githubusercontent.com/10268274/94389659-061f7300-0183-11eb-9104-e6353db1fbce.png)
![C2088_捐_256](https://user-images.githubusercontent.com/10268274/94389662-06b80980-0183-11eb-85e4-a654e8a6ee35.png)
and other font is
![C3844_碱_256](https://user-images.githubusercontent.com/10268274/94389708-30713080-0183-11eb-8f74-af5c183390fd.png)
![C4775_荷_256](https://user-images.githubusercontent.com/10268274/94389716-323af400-0183-11eb-9ac9-1949fb948f20.png)
![C5810_郗_256](https://user-images.githubusercontent.com/10268274/94389719-32d38a80-0183-11eb-9bfe-ac0a9ce3216b.png)
![C6265_霄_256](https://user-images.githubusercontent.com/10268274/94389721-336c2100-0183-11eb-9da8-1539dfa7b342.png)
![C2088_捐_256](https://user-images.githubusercontent.com/10268274/94389722-336c2100-0183-11eb-8b77-f45d41b2f304.png)
![C2232_攀_256](https://user-images.githubusercontent.com/10268274/94389725-3404b780-0183-11eb-9124-e378b363c9c2.png)
![C2366_晴_256](https://user-images.githubusercontent.com/10268274/94389727-349d4e00-0183-11eb-833d-a138a5360912.png)
![C3639_癜_256](https://user-images.githubusercontent.com/10268274/94389728-3535e480-0183-11eb-83ba-a33cfc830617.png)

I got the result for font1 is：
![font1_gen](https://user-images.githubusercontent.com/10268274/94389775-51d21c80-0183-11eb-8f1e-8243b3a485e5.png)

Would you plz try with two font testing ？？？ 
I want to know whether I make some problem or not about phase test ？

**Comment by 8uos** [comment]
Can you show us the results of the second font?
I wonder why you think the pretrained weight is not good, because I think it seems working well.

**Comment by Johnson-yue** [comment]
![font2_gen](https://user-images.githubusercontent.com/10268274/94393818-78498500-018e-11eb-82e9-5a1d9f42329d.png)

because I think the font1_gen not similarity to style of font1 （like the local feature about the hook at end of component）

and the font2_gen is a ... not good enough too

**Comment by SanghyukChun** [comment]
@Johnson-yue 
We remind our method of solving the few-shot font generation problem, not arguing about perfecting generation. Note that eight references are an astringent and harsh condition for reconstructing every local style as the real glyphs.

Our method mainly tackles major drawbacks of previous few-shot font generation tasks, such as "universal style representations". We thus validate our method on diverse test styles with convincing evaluation metrics. However, it does not guarantee that ours is always able to generate perfect glyphs. 

If you need a more high-quality font library for non-academic purposes, we suggest using a data-driven model (e.g., zi2zi), which requires additional finetuning with many references (e.g., > a few hundreds).

**Comment by Johnson-yue** [comment]
Your work has been very good. I am very curious about the effect generated on other fonts. Therefore, I have done some experiments to test the consistency between the generated style and the input style. I want to make sure that I understand your method and get the test results consistent with you. Maybe there is something wrong with my expression. I'm very sorry about said “not good”

**Comment by SanghyukChun** [comment]
@Johnson-yue 
IMO, your results seem consistent with our previous results. Most of their important information (content, thickness, serif-ness, ...) is well-preserved, although some details, e.g., hook, are missed.
From my previous experiences, I would assume that if you try other few-shot font generation models, the results will be much worse than these results.

As my previous comment, if you need better stylization for non-academic purposes, I would believe that either 
- you need more train styles (which is quite similar to your target style), or
- you need to fine-tune your model on the reference styles.

**Comment by Johnson-yue** [comment]
3Q， I will try it later
