### ISSUE TITLE
Did you consider using edge information？

### ISSUE THREAD

**Issue by Johnson-yue** [clovaai/lffont#13]
Hi， I test the model， it is good。 And I have some question about the framework：

1. some generated image  is blur and stroke is break， why did you not trying edge information for better performance？
2.  the generated image is smaller then input image， why？

**Comment by SanghyukChun** [comment]
**1. why did you not trying edge information for better performance?**

Thanks for your suggestion. We did not consider using edge information directly in our method.
Using edge information could be one of the future directions for this work, but now we don't consider using it.

**2. the generated image is smaller than the input image**

If you mean "smaller" in terms of pixel sizes, it is not a bug.
For example, your input is, say, 1024 x 1024 pixels, but the output is 128 x 128,
then it is our feature, not a bug. Our network uses resized 128 x 128 images.

**Comment by Johnson-yue** [comment]
@SanghyukChun  sorry about the question 2, it is not clear.
Let me recapitulate it....

I know the output image size is 128x128 ，it is fixed， I mean the unicode character outer size， is smaller than 128x128

**Comment by SanghyukChun** [comment]
@Johnson-yue 
Sorry for the late reply, I cannot sure why the phenomenon you asked about, but if I correctly understood your question, I presume that maybe most training examples have a relatively smaller size than your expected one.
A deep model trained in an end-to-end manner (as our method) could be tricky to debug or understand why a thing happens.

As a heuristic, I suggest you manually resizing your input to a larger resolution (e.g., 135 x 135) and apply center crop
```python
from torchvision import transforms
# assume x is a model output tensor
transform = []
# 135 is my random magic number. Please test various number
transform.append(transforms.Resize(135))
transform.append(transforms.CenterCrop(128))
my_transform = transforms.Compose(transform)

new_x = my_transform(x)
```

**Comment by Johnson-yue** [comment]
Thanks
