### ISSUE TITLE
How can I create decompose file(meta/chn_decompose.json) for another language? Japanese in my case.

### ISSUE THREAD

**Issue by nguyenvietbac** [clovaai/lffont#14]

**Comment by SanghyukChun** [comment]
Thanks for your question.
Unfortunately, there is no silver bullet to decomposition mappings.

For instance, we built the Chinese character decomposition table by using the following public CCD table
https://commons.wikimedia.org/wiki/Commons:Chinese_characters_decomposition

For complete-compositional languages such as Korean and Thai,
we parse Unicode to extract the component labels as follows:

- Korean: https://github.com/clovaai/dmfont/blob/master/datasets/kor_decompose.py#L29-L44
- Thai: https://github.com/clovaai/dmfont/blob/master/datasets/thai_decompose.py#L83-L101

For Japanse, as far as I know, you can use the CCD table for Kanji (there might be missing items in the CCD table, but as far as I know, most characters in popular Kanji are covered by the CCD table).

For Kana (Hiragana, Katakana), to my knowledge, there is no specific decomposition rule by its design. Hence, I suggest you manually build a new decomposition table for Kana (e.g., [dakuten](https://en.wikipedia.org/wiki/Dakuten_and_handakuten)) or treat them as an "atomic" (i.e., a character has only one component) for convenience.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming my answer resolves the problem.
Please re-open the issue as necessary.
