### ISSUE TITLE
I have three questions about the training details

### ISSUE THREAD

**Issue by clscy** [clovaai/lffont#17]
Hi, I'm so appreciate of your work. And I have three questions about the training details.
question one: when train the phase1 model, how choose training fonts to benefit to the convergence of the model ？
question two: first train the phase1 model, then initialize phase1, train the phase2 model, the technological process is right?
question three: almost training fonts don't include 371 components，whether need to update components json?
thank you .

**Comment by 8uos** [comment]
Hi,
Q1: We just eliminated the duplicated fonts.
Q2: Right.
Q3: If you want to use the model weight that we uploaded, you should use our decompose json file. 
New characters can be added to the file, but please remind that the defined component ids should be preserved.
If you are training a new model, you can build your own decompose json file.
Its format is a _dictionary_: {character name : [list of corresponding component ids]}.
The "character name" should be identical to the character name used in your lmdb dataset and meta files.
In this case, using different component ids ours is okay(In our case, 0 indicates ⺁, 1 indicates ⺌ ...).

**Comment by clscy** [comment]
ok, thank you.
