### ISSUE TITLE
I have a question about phase2

### ISSUE THREAD

**Issue by clscy** [clovaai/lffont#18]
Hi, in phase2, there is a function named check_and_sample, the trg_fonts is random choiced, and it's stype don't match to the in_fonts. Isn't it a bug?Thank you.
for example:
/media/chengls/Elements/lffont/images/in_img_3.jpg
/media/chengls/Elements/lffont/images/content_img_7.jpg
/media/chengls/Elements/lffont/images/trg_img_7.jpg
they are in_img、content_img and trg_img, but the style of trg_img is different from in_img.

**Comment by clscy** [comment]
![in_img_3](https://user-images.githubusercontent.com/22907560/106549896-ef33c780-654c-11eb-9c1e-d2ed6bd42918.jpg)
![content_img_7](https://user-images.githubusercontent.com/22907560/106549920-f65ad580-654c-11eb-9fdb-7c78283d2bf5.jpg)
![trg_img_7](https://user-images.githubusercontent.com/22907560/106549927-fb1f8980-654c-11eb-92aa-02ce6454a896.jpg)

**Comment by 8uos** [comment]
Hi, I have checked the code and tested it, and there was no error.

A possible mistake is calling dataset directly in multiple times, like this:
```python
dset = FactTrainDataset(...)
in_style_ids = dset[0][0]
trg_style_ids = dset[0][3]
...
```
Because the output of `dataset.__getitem__` changes every time you call it(because of random sampling), please modify the code like this:

```python
dset = FactTrainDataset(...)
batch = dset[0]
in_style_ids = batch[0]
trg_style_ids = batch[3]
...
```

or use the Dataloader defined in `datasets/__init__.py`

Sorry for the inconvenience.

**Comment by clscy** [comment]
Thank you for your reply。I mean that in the p2dataset.py, 
first, through the code on 122 line(self.sample_input(self.n_in_chars))，in_fonts will have three styles fonts(because self.n_in_chars = 3),
then in self.check_and_sample (...), the code on 113 line(trg_fonts = self.get_available_fonts(trg_unis, in_fonts)), for trg_unis, trg_fonts are random chosed based code on 55 line (avail_font = random.choice(avail_fonts)),.I think the operation will cause that trg_imgs possibly don't match to in_fonts.
for example:
in_fonts are ["fontA", "fontB", "fontC"], fontA include a component compA, fontB include a component compB, fontC include a component compC, 
but trg_imgs(s.t compnent imgs)  possibly occur that compA represent the style of fontB, not represent the style of fontA.
is it right? Thank you.

**Comment by 8uos** [comment]
I understood. It is right, not a bug. 
In phase 2, we aim to train the model to build new component-styles not included in input images("compA represent the style of fontB" of your example) through factorizing and combining the component-styles included in input images("compA represent the style of fontA ..." of your example).
So, what you are worrying about is what we intended to.
The detailed process is described in Section 3.3 of our [paper](https://arxiv.org/pdf/2009.11042).

Thanks for the question.

**Comment by clscy** [comment]
OK， thank you. In other words, in phase1 trg_imgs match to in_fonts, in phase2 may not match to in_fonts.
In your paper, the generated Style interpolation graphs is good, how is it generated?

**Comment by SanghyukChun** [comment]
@clscy 
I presume you mean the style interpolation figure (Fig 10, below)
<img width="656" alt="Screen Shot 2021-02-04 at 5 36 03 PM" src="https://user-images.githubusercontent.com/4919315/106866165-7b8de800-670f-11eb-8248-76da17bd7096.png">

We followed many previous style transfer literature for the style interpolation (e.g., AdaIN https://arxiv.org/abs/1703.06868)
More precisely, we generate the interpolated samples by
- `Decoder(content_features, content_factors, interpolated_style_factors)` where
- `content_features = ContentEncoder(content_glyph)`
- `content_factors = StyleEncoder_ContentFactorDecomposed(content_glyph, target_components)`
- `style_factors = StyleEncoder_StyleFactorDecomposed(reference_glyphs, reference_components)`
- `interpolated_style_factors = lambda * style_factors_1 + (1 - lambda) style_factors_2`, here lambda is between 0 and 1 (the figure shows the uniform lambda range), and style_factors_1 and style_factors_2 are from the most left / right fonts, respectively.

**Comment by clscy** [comment]
Ok, thank you.
