### ISSUE TITLE
how to test model with pretrained  weight

### ISSUE THREAD

**Issue by Johnson-yue** [clovaai/lffont#2]
Hi,  I see there is pertrained weight in weight/,  and I run the code like the ReadMe
![image](https://user-images.githubusercontent.com/10268274/94125105-83e43580-fe88-11ea-99a1-d985874c7d93.png)

But has error:

> lmdb.Error: /path/to/lmdb : No such file or directory 

because it find lmdb by defaults.yaml , and I did not modify it.

If I want to test pretrained weight, :  
  1)  I should write test.json first 
  2)  then make the lmdb file for test.json
  3)  modify the **data_path**  and **data_meta** in cfgs/defaults.yaml

?? Am I right?

As my opinion,  if I want to test the generator  it must be need content_font, so the it must be in **test_lmdb** file when Step2 (make it).

**Comment by 8uos** [comment]
Right.

The content font file we used can be accessed [here](https://chinesefontdesign.com/font-housekeeper-song-ming-typeface-chinese-font-simplified-chinese-fonts.html),
And we also added this link to the README.

Thanks for the comment.

**Comment by Johnson-yue** [comment]
@8uos  which name of font is "0250_simple" as defaults.yaml set,  plz tell me later . 3Q

**Comment by Johnson-yue** [comment]
3Q your reply ,I will test it

**Comment by Johnson-yue** [comment]
unicode = 4E34 not in chn_decompose.json 
This is common characters ,why did not exist?

![image](https://user-images.githubusercontent.com/10268274/94224142-34534780-ff24-11ea-8c73-c01ca517bae1.png)

**Comment by Johnson-yue** [comment]
When evaluate , 

1. I only make lmdb with test.json  which without trg_img for 'gen_unis' 
2. but  Evaluator -> get_fact_test_loader(**ret_target=True**)  (this is default) -> save_each_imgs return **trg_imgs** but never be used

Conclusion
if I make the 'gen_unis' as trg_img in lmdb  _(cost a lot of time for compare performance)_, it never be shown in result 
Would you plan to do some optimize about this **eval part** ?

**Comment by SanghyukChun** [comment]
Closing the issue, assuming #3 resolves the problem.
Please re-open the issue as necessary.

**Comment by SwordBearFire** [comment]
Hi, can you evaluate the pre-trained model successfully?
