### ISSUE TITLE
how to "Build meta file to dump lmdb environment" and how to "python build_dataset.py "?

### ISSUE THREAD

**Issue by pengyaru** [clovaai/lffont#21]
python build_dataset.py \
    --lmdb_path path/to/dump/lmdb \
    --meta_path path/to/meta/file \
    --json_path path/to/save/dict
can you give me an example of how to "Build meta file to dump lmdb environment" and how to "python build_dataset.py "?
because I just cant understand according to your description about "lmdb",   "meta file",,,

**Comment by 8uos** [comment]
Hi, thanks for your question.

First, you need a metafile that contains 1) the location of each font file, 2) a unique name for the font file, 3) list of characters to save from the font file.
I added the example of metafile in `meta/dataset.json`

To run `build_dataset.py`, three arguments are need; `meta_path`, `lmdb_path`, `json_path`.
`meta_path` is the path to the metafile described above.
`lmdb_path` and `json_path` are the paths where you want to save the dumped lmdb dataset and the json file (this is needed for the training).

If you have more questions, please notify me in this thread.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
