### ISSUE TITLE
During training, the model stops at "Start training..."

### ISSUE THREAD

**Issue by DYF-AI** [clovaai/lffont#22]
gpu: -1
INFO::07/07 13:42:05 | Unique name: NAME_phase1
INFO::07/07 13:42:05 | Get dataset ...
INFO::07/07 13:42:05 | Build model ...
INFO::07/07 13:42:14 | Start training ...

During training, the model stops at "Start training..."

**Comment by 8uos** [comment]
Hi.
What did you set the `print_freq` value to in the configuration file?
The first log will be displayed after the iterations that you set to `print_freq`.
In my case, it took about 15 minutes for 1000 iterations with a single V100 GPU and batch_size = 8.

**Comment by DYF-AI** [comment]
> Hi.
> What did you set the `print_freq` value to in the configuration file?
> The first log will be displayed after the iterations that you set to `print_freq`.
> In my case, it took about 15 minutes for 1000 iterations with a single V100 GPU and batch_size = 8.

print_freq: 1
![image](https://user-images.githubusercontent.com/54470509/124709838-89e66700-df2e-11eb-815f-1f3c1d3043aa.png)

**Comment by DYF-AI** [comment]
Is it caused by gpu=-1? , My GPU is 2080ti, I used GPU training

**Comment by 8uos** [comment]
No, the argument 'gpu' is for the DDP (DistributedDataParallel) training. 
gpu=-1 just means that you are not using DDP.

**Comment by DYF-AI** [comment]
![image](https://user-images.githubusercontent.com/54470509/124870304-0e032200-dff5-11eb-90f3-2d07e24fbb78.png)
![image](https://user-images.githubusercontent.com/54470509/124870316-13f90300-dff5-11eb-8d07-c169eb2aba54.png)
When the code runs to this place, it stops...

**Comment by DYF-AI** [comment]
Does this meta/chn_decompose.json need to be regenerated?

**Comment by DYF-AI** [comment]
> Does this meta/chn_decompose.json need to be regenerated?

  File "/source/code/dongyfy/code/AI/src/FontGeneration/lffont/datasets/p1dataset.py", line 67, in get_available_combinations
    comps = self.decompose_dict[uni]
KeyError: '995F'

**Comment by DYF-AI** [comment]
> Does this meta/chn_decompose.json need to be regenerated?

  File "/lffont/datasets/p1dataset.py", line 67, in get_available_combinations
    comps = self.decompose_dict[uni]
KeyError: '995F'

**Comment by 8uos** [comment]
The meta/chn_decompose.json file does not cover all the Chinese characters.
We referred to this [page](https://commons.wikimedia.org/wiki/Commons:Chinese_characters_decomposition) for constructing the meta/chn_decompose.json file.
However, the page was not perfect, so we excluded several characters containing noisy components.

If you want to use that character, the decomposition information of that character should be added to the JSON file.
You can get the decomposition file with original characters (not only with component ids) from [here](https://github.com/clovaai/mxfont/blob/main/data/chn_decomposition.json).
Note that the original components should be replaced with integer component ids after adding the character "995F" because this repository only supports the integer component ids.
Sorry for the inconvenience.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.

**Comment by EsperoComoAlas** [comment]
Sorry for the late reply. So do you mean that I need to choose the samples based on the target? If we have 8 targets(asuming including 16 components), all I'm supposed to do is picking some samples envolving the 16 components. Is that right? Should the samples be very big? (one component for 3 samples or more)?

For another ocassion,If the sample is universal, it seems to be a heavy task.  I have no idea to bulid the train set in that case.
Thanks for your help.

**Comment by 8uos** [comment]
Note that, our scenario is:
1) The model is trained with a large training dataset (We used 400+ fonts and 6000+ characters per font for the training set).
2) After 1), the trained model can generate any new font with few reference images, **without additional training**.

So, our model **does not require a few-shot training procedure or picking samples** for **generating new font images**.
However, if you want to train your own model weights, it is right that you need to pick samples considering the target characters' components and the sample set may be large in that case.
