### ISSUE TITLE
The label number of the chn_decomposed

### ISSUE THREAD

**Issue by simbadu1999** [clovaai/lffont#27]
Would you please tell me whether the chn_decomposed.json is created by yourself? And how can I know the number of the each component of the character? Thanks

**Comment by 8uos** [comment]
We provide the code to use the generated lmdb dataset in `dataset/lmdbutils.py`.
You can see how to use the provided functions in [here](https://github.com/clovaai/lffont/blob/00d90f1ff05bd30dde0a64276b6579e9c321b1bb/train.py#L139).

Sorry for the late reply.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
