### ISSUE TITLE
Question about the classfiers for calculating FID ACC(S) and ACC(C)

### ISSUE THREAD

**Issue by jmliu88** [clovaai/lffont#30]
Hi, thanks for the nice work! I have few questions about the evaluation classifiers while reading the paper. In your paper, you trained “style-aware (S) and content-aware (C) classifiers”. I'm curious about how they have been trained. 

Are they trained on both the seen and unseen fonts? If so, what are the training samples? Are all samples from training and testing datasets used to train the classifiers? And what architecture you were using for these classifiers?

Again, LFFont is a great work. Thanks a lot for your time.

James

**Comment by jmliu88** [comment]
Thanks for your reply. It helps!

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
