### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by zi1zi** [clovaai/lffont#37]
I need you to explain to see fonts, unseen fonts, see characters, unseen characters

**Comment by SanghyukChun** [comment]
They are already well-described in the paper and readme. Please check the documents and then clarify your question again.
As my previous comment, check our paper first https://arxiv.org/abs/2009.11042

> If your question is related to the seen/unseen fonts/characters, please read the paper Section 4.1, or other issues such as https://github.com/clovaai/lffont/issues/1

https://github.com/clovaai/lffont#build-meta-file-to-train-and-test

**Comment by zi1zi** [comment]
Hello, I haven't run your code yet, I took a rough look at the preparations before running the code, and I have the following questions:
1. Is there a training set and a verification set divided in this experiment? If so, why is the valid field in train.json different from the train field in form? Why is it not of the type {font: list of characters}?
2.seen fonts(unis) is used for training, unseen fonts(unis) is used for verification or evaluation, unseen fonts are font types that have not been seen in training, and font types that have not been seen in training can be generated during evaluation ?

**Comment by zi1zi** [comment]
Hello, I haven't run your code yet, I took a rough look at the preparations before running the code, and I have the following questions:
1. Is there a training set and a verification set divided in this experiment? If so, why is the valid field in train.json different from the train field in form? Why is it not of the type {font: list of characters}?
2. Although --lmdb_path, --meta_path, --json_path have made a clear description, but still do not understand, which file does the three paths refer to?
3.seen fonts (unis) is used for training, unseen fonts (unis) is used for verification or evaluation, unseen fonts are font types that have not been seen in training, and font types that have not been seen in training can be generated during evaluation ?
4. Why is ref_unit in test.json part of the unseen character set of the valid field in train.json, and what is gen_unis?
