### ISSUE TITLE
KeyError : "XXXX" when valid phase 

### ISSUE THREAD

**Issue by Johnson-yue** [clovaai/lffont#6]
when I train phase 1 , this error occur in [here](https://github.com/clovaai/lffont/blob/f31f5a1cd6a075449a0f18aaafd945d373121e15/datasets/p1dataset.py#L183)

I debug it  and the local variables self.availds.keys()  is ["seen_fonts", "unseen_fonts", "seen_unis", "unseen_unis"] 
 maybe this is a bug ?

**Comment by 8uos** [comment]
Thank you for the comment.
We have merged your pull requests, and also updated the dataset for phase 2 training.
If you have any other problems for training, comment us again please.
